MIT License

Copyright (c) THOMAS CATALANO
;
Copyright (c) */* THOMAS JOSEPH CATALANO(135-74-4812;DOB:1981-02-05) */* */* _holdings_ */* *GROUP/SYSTEM/* */\.
;
Copyright (c) */* THOMAS CATALANO */* */* _holdings_ */* */SYSTEM/GROUP/* */\.
;
Copyright (c) The Letter of Proof */* _holdings_ */* */SYSTEM/GROUP/* */\.
;
Copyright (c) BIT(s);"BIT(s)"(information/time/frames) */* _holdings_ */* */SYSTEM/FOUNDATION/GROUP/* */\.
;
Copyright (c) BIT(s);"BIT(s) "LICENSE""\.
;
Copyright (c) BIT(s) */* _holdings_ */* */* */\.
;
Copyright (c) BIT(s);"BIT(s)" */* _holdings_ */* */* */\.
;
Copyright (c) ALTUSNET\.
;
Copyright (c) "cryptocurrency" */* cryptocurrency((blockchain;algorithm)&|"like") */* */* _holdings_ */* */\.
;
Copyright (c) "https://"\.
;
Copyright (c) "http://"\.
;
Copyright (c) "www."\.
;
Copyright (c) 
;
Copyright (c) "Ph.D"\.
;
Copyright (c) Ph.D/Ph.D. */* _holdings_ */* */licensing/SYSTEM/* */non-profit\.
;
Copyright (c) "Ph.D."\.
;
Copyright (c) "PhD"\.
;
Copyright (c) PhD */* _holdings_ */* */SYSTEM/* */non-profit\.
;
Copyright (c) */* Physics/Chemistry/Numerical-Comp */* */* _holdings_ */* */SYSTEM/FOUNDATION/GROUP/* */\.
;
Copyright (c) "?"\.
;
Copyright (c) "'"\.
;
Copyright (c) "+"\.
;
Copyright (c) ""-""\.
;
Copyright (c) "×"\.
;
Copyright (c) "÷"\.
;
Copyright (c) """"""\.
;
Copyright (') """\.
;
Copyright (c) "-"\.
;
Copyright (c) "_"\.
;
Copyright (c) "<>"\.
;
Copyright (c) "[]"\.
;
Copyright (c) "{}"\.
;
Copyright (c) "!!'\.
;
Copyright (c) "|"\.
;
Copyright (c) "||"\.
;
Copyright (c) "@"\.
;
Copyright (c) "=="\.
;
Copyright (c) "&"\.
;
Copyright (c) "&|"\.
;
Copyright (c) "&&"\.
;
Copyright (c) "="\.
;
Copyright (c) "%"\.
;
Copyright (c) "%%"\.
;
Copyright (c) "#"\.
;
Copyright (c) "!"\.
;
Copyright (c) """"\.
;
Copyright (c) ","\.
;
Copyright (c) "/"\.
;
Copyright (c) "\"\.
;
Copyright (c) ";"\.
;
Copyright (c) "*"\.
;
Copyright (c) "~"\.
;
Copyright (c) "()"\.
;
Copyright (c) ""\.
;
Copyright (c) "."\.
;
Copyright (c) ":"\.
;
Copyright (c) git-src */* _holdings_ */* */ */non-profit\.
;
Copyright (c) src-git */* _holdings_ */* */GROUP */non-profit\.
;
Copyright (c) github */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) git/github/github.com/tomsnode\.
;
Copyright (c) git/github/github.com/conceptslearningmachine\.
;
Copyright (c) git/github/github.com/ALTUSNETS\.
;
Copyright (c) git/github/github.com/TheBitMarket\.
;
Copyright (c) CLM ~ Concepts Learning Machine */* _holdings_ */* */Limited Liability Company*/ */\.
;
Copyright (c) Catalano Ltd.\.
;
Copyright (c) ALTUSNET */* _holdings_ */* */Limited Liability Company/* */\.
;
Copyright (c) Catalano Concepts */* _holdings_ */* */Limited Liability Company/* */\.
;
Copyright (c) conceptslearningmachine\.
;
Copyright (c) Catalano\.
;
Copyright (c) github/github.com/github _holdings_ */GROUP/Corporation/* */INC./LLC./non-profit\.
;
Copyright (c) ALTUSNET _holdings_ Limited Liability Company\.
;
Copyright (c) www.conceptslearningmachine.com\.
;
Copyright (c) linux _holdings_ */* */GROUP/SYSTEM/* */non-profit\.
;
Copyright (c) SElinux */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) gnu */* _holdings_ */* */ */non-profit\.
;
Copyright (c) gcc */* _holdings_ */* */ */non-profit\.
;
Copyright (c) MOTOROLA */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) LLVM */* _holdings_ */* */ */non-profit\.
;
Copyright (c) POSIX */* _holdings_ */* */SYSTEM/GROUP/* */non-profit\.
;
Copyright (c) ARM */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) INTEL */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) NIVIDIA */ _holdings_ */* */GROUP/CORPORATION/* */INC./LLC.\.
;
Copyright (c) Dell */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) HP */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) AMD */* _holdings_ */*  */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) IBM */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) MICROSOFT */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) Lockheed Martin */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) GE */* _holdings_ */* */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) CHASE BANK _holdings_ GROUP/CORPORATION */INC./LLC./non-profit\.
;
Copyright (c) Wells Fargo Bank _holdings_  */INC./LLC.\.
;
Copyright (c) Boeing _holdings_ Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) BASF _holdings_ Corporation/GROUP */Ltd./INC./LLC.\.
;
Copyright (c) NYSE _holdings_ Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) NASDAQ _holdings_ GROUP/Corporation */INC./LLC./non-profit\.
;
Copyright (c) Space X _holdings_ */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) Alenia Aeronautica _holdings_  */GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) Vanguard _holdings_ */GROUP/* */INC./LLC./non-profit\.
; 
Copyright (c) Vanguard Mutual _holdings_ */GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) NAVIENT/Navient Solutions _holdings_ */GROUP/CORPORATION/* */INC./LLC./non-profit\.
;
Copyright (c) Market Exchange GROUP */INC./LLC./non-profit\.
;
Copyright (c) Bank of America _holdings_ */GROUP*/Corporation/* */INC./LLC./non-profit\.
;
Copyright (c) Morgan Stanley _holdings_ */Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) U.S. Securities Exchange _holdings_ Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) CNN _holdings_ Broadcasting _holdings_ Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) US Treasury NOTE */* _holdings_ */* */* "currency" */* */GROUP/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) National Broadcasting Company (NBC) */* _holdings_ */* */Corporation/GROUP */INC./INC./non-profit\.
;
Copyright (c) MARVEL / MARVEL CINEMATIC UNIVERSE Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) Warner Brothers _holdings_ Studio's _holdings_ Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) GOOGLE _holdings_ */Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) US Naval Research Laboratory (NRL) _holdings_ */Corporation/GROUP/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) US Army Research Laboratory (ARL) _holdings_ */GROUP/Corporation/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) PIMCO HOLDINGS _holdings_ */GROUP/Corporation/* */INC./LLC./non-profit\.
;
Copyright (c) Motion Picture Association of America */* !_holdings_! */* */ */INC./LLC./non-profit\.
;
Copyright (c) */* */US/* */* PATENT & TRADEMARK */* _holdings_ */* */Account/Papers/Writings/Format/SYSTEM/GROUP/* */ */non-profit\.
;
Copyright (c) USAA _holdings_ */ */INC./LLC./non-profit\.
;
Copyright (c) General Motors (GM) */* "cars/trucks/automobiles/vehicles" */* */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) FORD MOTOR COMPANY */* _holdings_ */* Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) American Express (AMX) _holdings_ Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) MASTERCARD _holdings_ GROUP/CORPORATION/* */INC./LLC./non-profit\.
;
Copyright (c) GE Capital _holdings_ Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) Alitalia _holdings_ Corporation/GROUP */INC./LLC./non-profit\.
;
Copyright (c) NASDAQ E GROUP _holdings_ GROUP/Corporation */INC./LLC./non-profit\.
;
Copyright (c) CHURCH OF ENGLAND _(Great Britain)_ _holdings_ */GROUP/SYSTEM/* */\.
;
Copyright (c) BANK OF CHINA _holdings_ Corporation/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) The Vatican Bank/Vatican/The Holy See _(AIF)_ _(IOR)_  _holdings_ */GROUP/SYSTEM/* */non-profit\.
;
Copyright (c) Financial Intelligence Authority (AIF) _holdings_ */GROUP/Corporation */INC./LLC./non-profit\.
;
Copyright (c) VC NEWS COMPANY _holdings_ */GROUP/CORPORATION */INC./LLC./non-profit\.
;
Copyright (c) Daimler/Daimler-Benz/Benz/Mercedes-Benz/AMG _holdings_ */GROUP/CORPORATION/* */INC./LLC./non-profit\.
;
Copyright (c) FIAT _holdings_ */GROUP/CORPORATION/* */INC./LLC./non-profit\.
;
Copyright (c) ASTON MARTIN COACH WORKS _holdings_ GROUP/CORPORATION */INC./LLC./non-profit\.
;
Copyright (c) VW GROUP _holdings_ GROUP/CORPORATION/* */INC./LLC./non-profit\.
;
Copyright (c) HBO _holdings_ GROUP/Corporation/* */INC./LLC./non-profit\.
;
Copyright (c) GM _holdings_ GROUP/Corporation */INC./LLC./non-profit\.
;
Copyright (c) Civil Engineer */* _holdings_ */* */GROUP/Corporation/* */INC.LLC./non-profit\.
;
Copyright (c) US Air Force Research Laboratory (AFRL) _holdings_ */GROUP/Corporation/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) US Space Force Research Laboratory (SFRL) _holdings_ */GROUP/Corporation/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) */* UNITED NATIONS (UN) */* _(UN)_ */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) */* INTERNATIONAL COURT OF JUSTICE/COURT OF INTERNATIONAL JUSTICE */* (ICJ-CIJ) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) */* NORTH ATLANTIC TREATY ORGANIZATION(NATO) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) European Space Agency (ESA) */* _(_ESA_)_ */* */* _(_esa_)_ */* */* _holdings_ */GROUP/CORPORATION/* */* _entity_ */* */INC./LLC./non-profit\.
;
Copyright (c) */* National Aeronautics & Space Agency (NASA) */* */* _(_NASA_)_ */* */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */* _entity_ */* */INC./LLC./non-profit\.
;
Copyright (c) */* North American Aerospace Defense (NORAD) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) */* Antarctic Treaty System(ATS) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) INTERNATIONAL STANDARDS ORGANIZATION (ISO) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY (NIST) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */INC./LLC./non-profit\.
;
Copyright (c) */* INTERNATIONAL BAR ASSOCIATION (IBA) */* */* "Esq" */* */* _holdings_ */* */GROUP/SYSTEM/* */*\.
;
Copyright (c) */* network time protocol (NTP) (ntp/.ntp) */* _holdings_  */* */GROUP/SYSTEM/CORPORATION/* */INC./LLC./non-profit\.
;
Copyright (c) EARTH */* "EARTH" */* _planet_ Earth */* "Earth" */* _holdings_ */* */SYSTEM/GROUP/TERAGEOASTROSPACE/* */*\.
;
Copyright (c)  */* _SPACE_ _CONTINUUM_ */* "Space Continuum" */* Space-Continuum */ SpaceContinuum */* _space__continuum_ */* _holdings_ */* */SYSTEM/FOUNDATION/GROUP/* */\.
;
Copyright (c) */* _human_ _anatomy_ _anatomics_ */* _human__anatomy_ */* human-anatomy */* ""human" "anatomy"" */* _holdings_ */* */SYSTEM/FOUNDATION/GROUP(S)/* */\.
;
Copyright (c) _entity_ */* THE UNITED STATES OF AMERICA */* UNITED STATES */* TheUnitedStatesOFAmerica */* */* _(_USA_)_ */* */* _(_US_)_ */* */* _(_U.S.A_)_ */* */ _(_U.S._)_ */* /* "telecom_country-code;US:(+1)\."  */* "The United States of America" */* */* United States */* */* _holdings_ */* */* _entity_ */* *STATE/COUNTRY//SYSTEM/GROUP/FORTHRIGHT/* _entity_ */\.
;
Copyright (c) ACME */* _holdings_ */* */* _holders_ */* */CORPORATION/GROUP/* */INC./LLC./non-profit\.
;
Copyright (c) WORLD BANK GROUP */* _holdings_ */* */GROUP/SYSTEM/* */non-profit\.
;
Copyright (c) International Monetary Fund (IMF) */* _holdings_ */* */GROUP/SYSTEM/CORPORATION/* */non-profit\.
;
Copyright (c) Group of Seven (G7) */* _holdings_ */* */GROUP/SYSTEM/FORTHSET/* */non-profit\.
;
Copyright (c) Federation International of Automobile (FIA) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) National Football League (NFL) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM*/ */\.
;
Copyright (c) Federation International of Football Association (FIFA) (fifa) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) National Basketball Association (NBA) */* _holdings_ */* GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) Major League Baseball (MLB) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) National Hockey League (NHL) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) Formula One (F1) */* "automobile" */* */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) The 24hrs of Le Mans () */* automobile" */* */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) National Association for Stock Car Racing (NASCAR) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) The International Olympic Committee (IOC) (CIO) (NOC) */ _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) TeamUSA (USOC) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) America Broadcasting Company (ABC) */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) Scudaria Ferrari */* Ferrari */* */* _holdings_ */* */GROUP/CORPORATION/SYSTEM/* */\.
;
Copyright (c) Automobiles Ettore Bugatti */* Bugatti */* */* _holdings_ */* */GROUP/CORPORATION/* */\.

All rights reserved.    

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
