©>;;::;*'THOMAS CATALANO'*;;::;;;


,\THE;PROCESS OF GERMATANING APPARATUS;:MAPCOING ATOMS TO EXPIDABLE CONDTIONS;:;TO RENDER (AS OCCURED WITH THE PLANET EARTH,FOR REASONS OF TIME-TRAVELING-TRSNSPORTATION
