©\/,::,


,::.\,:APPARATUS UTILIZING TWO OPPOSING-OPERAND GYROSCOPING-ASTROSTELER-RESIGNATOR-ENCAPSULATED-GEARED-WORM-RING -SKU'D- GYROSCOPE-FORK-DIFIBULATOR-HOSE ITER-CONNECT



,::.\/©\/,:'THOMAS CATALANO,Ph.Doctor',\/©\/ <<>> \/©
