©\/,::,


,::.\,:APPARATUS UTILIZING TWO OPPOSING-OPERAND GYROSCOPING-ASTROSTELER-RESIGNATOR ENCAPSULATED-WORM-GEAR-RING -SKU'D- GYROFORK-DIFIBULATOR-HOSE ITER-CONNECT



,::.\/©\/,:'THOMAS CATALANO',\/©\/ <<>> \/©
