©\/,::,


,::.\,:APPARATUS UTILIZES TWO OPPOSING-OPERAND GYROSCOPING-ASTROSTELLER-RESIGNATOR-ENCAPSULATED-GEARED-WORM-RING -SKU'D- GYROSCOPE-FORK-DIFIBULATOR-HOSE ITER-CONNECT



,::.\/©\/,:'THOMAS CATALANO,Ph.Doctor',\/©\/ <<>> \/©
