©\/,::,


,::.\,:TELEPORTATION-BIPOLESITION-DUALITY-COMPLIANT-APPARATUS UTILIZES TWO OPPOSING-OPERAND GYROSCOPING-ASTROSTELLER.SHELL-RESIGNATOR-ENCAPSULATED-TIMING-GEARED-WORM-RING-SCUBACENTRIC -SKU'D- GYROSCOPE-FORK-DIFIBULATOR-HOSE.TUB-.ITER-CONNECT\/,:



,::.\/©\/,:'THOMAS CATALANO,Ph.Doctor',\/©\/ <<>> \/©
