©\/,::,


,::.\,:TELEPORTATION-BIPOLESITION-APPARATUS UTILIZES TWO OPPOSING-OPERAND GYROSCOPING-ASTROSTELLER.SHELL-RESIGNATOR-ENCAPSULATED-TIMING-GEARED-WORM-RING-SCUBACENTRIC -SKU'D- GYROSCOPE-FORK-DIFIBULATOR-HOSE ITER-CONNECT



,::.\/©\/,:'THOMAS CATALANO,Ph.Doctor',\/©\/ <<>> \/©
